PolicyManagement/Controllers/ClientController.cs
using PolicyManagement.Services.Interface;
using System.Web.Mvc;

namespace PolicyManagement.Controllers
{
    public class ClientController : Controller
    {
        private IClientService clientService;

        public ClientController(IClientService service)
        {
            clientService = service;  
        }
        // GET: Client
        [Authorize]
        public ActionResult Index()
        {
            var clients = clientService.GetAll();
            return View(clients);
        }

        // GET: Client/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var client = clientService.GetId(id);
            return View(client);
        }

        // GET: Client/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // GET: Client/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var client = clientService.GetId(id);
            return View(client);
        }
    }
}

PolicyManagement/Controllers/PolicyController.cs
using PolicyManagement.Services.Interface;
using System.Web.Mvc;

namespace PolicyManagement.Controllers
{
    public class PolicyController : Controller
    {
        private IPolicyService policyService;

        public PolicyController(IPolicyService service)
        {
            policyService = service;
        }
        // GET: Policy
        [Authorize]
        public ActionResult Index()
        {
            var policies =  policyService.GetAll();
            return View(policies);
        }

        // GET: Policy/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var policy = policyService.GetId(id);
            return View(policy);
        }

        // GET: Policy/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // GET: Policy/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var policy = policyService.GetId(id);
            return View(policy);
        }
    }
}

PolicyManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pólizas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pólizas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Póliza", "Index", "Policy")</li>
                        <li>@Html.ActionLink("Clientes", "Index", "Client")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>